name: Release

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    call-release:
        name: Call Plugin Release Workflow
        uses: Studio-Lemon/workflows/.github/workflows/plugin-release.yml@main
        with:
            plugin_name: 'lemon-woo'
        secrets: inherit
