name: Release

on:
    workflow_dispatch:

jobs:
    call-release:
        uses: Studio-Lemon/workflows/.github/workflows/release-plugin/release.yml@main
        with:
            plugin_name: 'lemon-woo'
        secrets: inherit
