name: Release

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
  create_zip:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build plugin # Remove or modify this step as needed
      run: |
        npm install
        npm run build
    - name: Create zip archive
      run: |
        git archive --format=zip HEAD -o lemon-woo.zip
        mkdir lemon-woo
        unzip lemon-woo.zip -d lemon-woo
        rm lemon-woo.zip
        cp -r dist lemon-woo
        zip -r lemon-woo.zip lemon-woo
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          lemon-woo.zip