name: Release

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
  create_zip:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

#    - name: Build plugin # Remove or modify this step as needed
#      run: |
#        composer install --no-dev
#        npm install
#        npm run build
    - name: Create zip archive
      run: |
        git archive --format=zip HEAD -o lemon-woo.zip HEAD
        echo "::set-output name=zip_path::lemon-woo.zip"
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          lemon-woo.zip